### ISSUE TITLE
Demo link is down Luke

### ISSUE THREAD

**Issue by yanna92yar** [lukeocodes/deeptube#2]

**Comment by lukeocodes** [comment]
It's working for me?

**Comment by yanna92yar** [comment]
The one on Vercel ? 
It returns: 

> 404: NOT_FOUND
> Code: DEPLOYMENT_NOT_FOUND

I'm in France and generally no problems of accessibility at all.

**Comment by lukeocodes** [comment]
Ahh the vercel one didn't work, I moved it to fly.io

https://deepgram-youtube-demo.fly.dev/

I thought I updated all the links
